// server/utils/eventTypes.ts
export enum AuditAction {
  // User
  USER_REGISTER = "USER_REGISTER",
  USER_LOGIN = "USER_LOGIN",
  USER_LOGOUT = "USER_LOGOUT",
  USER_UPDATE_PROFILE = "USER_UPDATE_PROFILE",
  USER_CHANGE_PASSWORD = "USER_CHANGE_PASSWORD",
  // Ads
  AD_CREATED = "AD_CREATED",
  AD_UPDATED = "AD_UPDATED",
  AD_DELETED = "AD_DELETED",
  AD_STATUS_CHANGED = "AD_STATUS_CHANGED", // approve/reject
  AD_VIEWED = "AD_VIEWED", // optional
  // Wallet & Payments
  WALLET_CHARGED = "WALLET_CHARGED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  // Subscription
  SUBSCRIPTION_PURCHASED = "SUBSCRIPTION_PURCHASED",
  SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED",
  // Ticket
  TICKET_CREATED = "TICKET_CREATED",
  TICKET_REPLIED = "TICKET_REPLIED",
  // Report
  REPORT_CREATED = "REPORT_CREATED",
  // Admin actions
  ADMIN_USER_BAN = "ADMIN_USER_BAN",
  ADMIN_USER_UNBAN = "ADMIN_USER_UNBAN",
  ADMIN_ROLE_CHANGE = "ADMIN_ROLE_CHANGE",
  // etc...
}
